version: "3.5"

services:
# ZOOKEEPER ------------------------------------------------------------------------
# "`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-
#
# Orchestratore degli elementi del sistema KAFKA
#
   zookeeper:
    image:  wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
      
# KAFKA-BROKER 1 INSIDE://kafka_1:9093,OUTSIDE://localhost:9092------------------------------------------------------------------------
# "`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-
#
# Vengono definiti i broker Kafka con relative porte esposte internamente alla rete Docker 
# per la connessione tra container e le porte esposte esternamente per permettere la connessione
# ad applicativi esterni alla rete Docker
#
# "`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-
   kafka_1:
    image: wurstmeister/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    expose:
      - "9093" 
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka_1:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE

# KAFKA-BROKER 2 INSIDE://kafka_2:9095,OUTSIDE://localhost:9094------------------------------------------------------------------------
# "`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-
#
# Vengono definiti i broker Kafka con relative porte esposte internamente alla rete Docker 
# per la connessione tra container e le porte esposte esternamente per permettere la connessione
# ad applicativi esterni alla rete Docker
#
# "`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,- 
   kafka_2:
      image: wurstmeister/kafka:latest
      depends_on:
         - zookeeper
      ports:
         - "9094:9094"
      expose:
         - "9095" 
      environment:
         KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka_2:9095,OUTSIDE://localhost:9094
         KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
         KAFKA_LISTENERS: INSIDE://0.0.0.0:9095,OUTSIDE://0.0.0.0:9094
         KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
         KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE

# KAFKA-BROKER 3 INSIDE://kafka_3:9097,OUTSIDE://localhost:9096------------------------------------------------------------------------
# "`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-
#
# Vengono definiti i broker Kafka con relative porte esposte internamente alla rete Docker 
# per la connessione tra container e le porte esposte esternamente per permettere la connessione
# ad applicativi esterni alla rete Docker
#
# "`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-
   kafka_3:
      image: wurstmeister/kafka:latest
      depends_on:
         - zookeeper
      ports:
         - "9096:9096"
      expose:
         - "9097" 
      environment:
         KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka_3:9097,OUTSIDE://localhost:9096
         KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
         KAFKA_LISTENERS: INSIDE://0.0.0.0:9097,OUTSIDE://0.0.0.0:9096
         KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
         KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
